### ISSUE TITLE
可以提供该项目所需的所有依赖包吗？requirements.txt包含的依赖不全

### ISSUE THREAD

**Issue by aaalionaaa** [DemoGit4LIANG/Chat2Anything#2]

**Comment by allenpubgit** [comment]
OK, I will check the dependencies and provide an updated requirements.txt if necessary.

**Comment by aaalionaaa** [comment]
> OK, I will check the dependencies and provide an updated requirements.txt if necessary.

好的，谢谢。如果可以的话，能否把部署该项目的步骤写得更详细些
