### ISSUE TITLE
項目不錯

### ISSUE THREAD

**Issue by liangjhanyuan** [DemoGit4LIANG/Chat2Anything#4]
但是admin那塊教程我遇到一些問題裝不起來，直接使用docker compose up，flask會有錯誤， 如果教程能再詳細一點就更好了，感謝。

**Comment by allenpubgit** [comment]
> 但是admin那塊教程我遇到一些問題裝不起來，直接使用docker compose up，flask會有錯誤， 如果教程能再詳細一點就更好了，感謝。

直接运行就可以了，docker不是必须的哈
